# Generated by Django 5.2.1 on 2025-05-30 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, unique=True)),
                ('place_address', models.TextField()),
                ('place_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
            ],
            options={
                'db_table': 'workplaces',
                'ordering': ['place_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.DateField()),
                ('work_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hours.workplaces')),
            ],
            options={
                'db_table': 'working_hours',
                'ordering': ['work_day'],
                'unique_together': {('work_day', 'user')},
            },
        ),
    ]
